-- In-memory (H2) schema. Shared by both the jOOQ and the JPA/ORM data-access layers.
CREATE TABLE IF NOT EXISTS time_access_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_mode VARCHAR(16)              NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
